### ISSUE TITLE
Application for Data Processing Source Code

### ISSUE THREAD

**Issue by zizzizziz** [CIOL-SUST/SupplyGraph#1]
Dear Azmine Toushik Wasi,

Thank you very much for providing access to this dataset. I am deeply interested in it and plan to conduct some combinatorial optimization work based on this dataset. However, I am currently unable to locate your paper, and as such, I am writing to request the source code related to data processing mentioned in your paper. I greatly appreciate your help and look forward to a positive response.

Sincerely,
ZIZ

**Comment by azminewasi** [comment]
The paper is available here: https://arxiv.org/abs/2401.15299
Data pre-processing codes will not be released, as they have confidential company information. We have pre-processed them to remove any confidential information.
