### ISSUE TITLE
Unclear semantics of edge data

### ISSUE THREAD

**Issue by mgns** [CIOL-SUST/SupplyGraph#3]
Hello, we are trying to recreate the graphs you published here. Though, it is unclear how to read the edges files in order to resemble a valid graph.
Take e.g. Edges (Plant).csv consists of columns: Plant | node1 | node2
I assume the edges are typed and directed. What is the edge type in this case? Do I assume correctly the there is an edge pointing from node1 to node2?

**Comment by azminewasi** [comment]
It really depends on the perspective. 

In that case, we assumed that if node1 and node2 shared a plant - they are connected, in a undirected fashion.

**Comment by mgns** [comment]
Sorry, but which perspectives do you mean?

You cannot simply connect nodes in an arbitrary way. Connecting two products because they are produced in the same plant does not make any sense! You would rather want to connect the two product nodes to the plant node using a directed 'is-produced-in' edge. We are struggling to construct a proper graph from the published data.

**Comment by azminewasi** [comment]
Yes, we can and it makes sense too.
If a plant's total production capacity is X, and it produces two products A and B. Then, we can say Production_A + Production_B = X, when the factory is consistently running in full production capacity. So, if Production_A rises, Production_B will fall; and vice versa. So, there is obviously a relation there. 
But, it is upto the researcher to consider it or not. This is the perspective I am referring to. 
There are a lot things can be done, but it depends solely on the perspective of the researcher.

I hope it clears your confusion.

**Comment by mgns** [comment]
Okay, then I totally misunderstood your approach. We are looking into property graphs, where connections between nodes have a clear meaning.
